name: Main CI

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions:
    contents: write
on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup job
              uses: ./.github/actions/install-dependencies
            - name: Run Eslint
              run: pnpm run lint

    build:
        name: Build Package
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup job
              uses: ./.github/actions/install-dependencies
            - name: Run SWC
              run: pnpm run build

    types:
        name: Check types
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup job
              uses: ./.github/actions/install-dependencies
            - name: Run tsc
              run: pnpm run types:ci

    test:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup job
              uses: ./.github/actions/install-dependencies
            - name: Run Tests
              run: pnpm run test:ci

    release:
        name: Release
        runs-on: ubuntu-latest
        needs: [lint, build, test, types]
        if: false

        steps:
            - uses: actions/checkout@v3
            - name: Setup job
              uses: ./.github/actions/install-dependencies

            - name: Build Package
              run: npm run build

            - name: Release
              id: semantic
              uses: cycjimmy/semantic-release-action@v3.4.0
              env:
                  HUSKY: 0
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

        outputs:
            new_release_published: ${{ steps.semantic.outputs.new_release_published }}
            new_release_version: ${{ steps.semantic.outputs.new_release_version }}
